//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLog.Objects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResourcesHRV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResourcesHRV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookLog.Objects.Resources.ViewResourcesHRV", typeof(ViewResourcesHRV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string KorisnickoIme {
            get {
                return ResourceManager.GetString("KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string KorisnickoIme_Placeholder {
            get {
                return ResourceManager.GetString("KorisnickoIme_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo tvrtke Apple.
        /// </summary>
        public static string Login_AppleLogo {
            get {
                return ResourceManager.GetString("Login_AppleLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple prijava.
        /// </summary>
        public static string Login_ApplePrijava {
            get {
                return ResourceManager.GetString("Login_ApplePrijava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli na BookLOG!.
        /// </summary>
        public static string Login_Dobrodosli {
            get {
                return ResourceManager.GetString("Login_Dobrodosli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo tvrtke Google.
        /// </summary>
        public static string Login_GoogleLogo {
            get {
                return ResourceManager.GetString("Login_GoogleLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google prijava.
        /// </summary>
        public static string Login_GooglePrijava {
            get {
                return ResourceManager.GetString("Login_GooglePrijava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Područje za unos korisničkog imena.
        /// </summary>
        public static string Login_KorisnickoIme {
            get {
                return ResourceManager.GetString("Login_KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo prikazuje četiri knjige poslagane jedna na drugu.
        /// </summary>
        public static string Login_LogoAltTekst {
            get {
                return ResourceManager.GetString("Login_LogoAltTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Područje za unos lozinke.
        /// </summary>
        public static string Login_Lozinka {
            get {
                return ResourceManager.GetString("Login_Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli natrag na BookLOG - Nedostajali ste nam ❤.
        /// </summary>
        public static string Login_PrijaviteSe {
            get {
                return ResourceManager.GetString("Login_PrijaviteSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slažem se s Pravilima privatnosti.
        /// </summary>
        public static string Login_SuglasnostPrivatnosti {
            get {
                return ResourceManager.GetString("Login_SuglasnostPrivatnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string Lozinka_Placeholder {
            get {
                return ResourceManager.GetString("Lozinka_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string Naslov {
            get {
                return ResourceManager.GetString("Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Prijava {
            get {
                return ResourceManager.GetString("Prijava", resourceCulture);
            }
        }
    }
}
